# SPDX-FileCopyrightText: 2026 Nikolay Govorov
# SPDX-License-Identifier: AGPL-3.0-or-later

min_version = "2026.7.5"

[settings]
experimental = true

[tools]
buf = "1.67.0"
gh = "2.96.0"
go = "1.26.6"
node = "24.18.0"
task = "3.52.0"   # Removed after Taskfile.yml is migrated to mise tasks.
zig = "0.16.0"

[bootstrap.packages]
# APT
"apt:apt-utils" = "latest"
"apt:createrepo-c" = "latest"
"apt:debsigs" = "latest"
"apt:gnupg" = "latest"
"apt:openssl" = "latest"
"apt:rpm" = "latest"
"apt:zip" = "latest"

# DNF
"dnf:createrepo_c" = "latest"
"dnf:gnupg2" = "latest"
"dnf:openssl" = "latest"
"dnf:rpm" = "latest"
"dnf:zip" = "latest"

[task_config]
dir = "{{cwd}}"
includes = [
  "git::https://github.com/dimidiumlabs/infra.git//tasks?ref=8bc35fe8be889c50db2d1fb4425cc1b4097dc6b8",
]
