# Copyright (c) 2026 Nikolay Govorov
# SPDX-License-Identifier: AGPL-3.0-or-later

version = 1

[[annotations]]
path = [
  "go.mod",
  "go.sum",
  "VERSION",
  "CLA.md",
  "CONCEPT.md",
  "README.md",
  "pkg/logo.svg",
  "pkg/dl/*",
  "proto/buf.*",
  "cmd/mirumd/web/*.json",
]
SPDX-FileCopyrightText = "2026 Nikolay Govorov <me@govorov.online>"
SPDX-License-Identifier = "AGPL-3.0-or-later"
