# Copyright (c) 2026 Nikolay Govorov
# SPDX-License-Identifier: AGPL-3.0-or-later

version = 1

[[annotations]]
path = [
  ".mailmap",
  "CLA.md",
  "VERSION",
  "cmd/mirum-server/web/*.json",
  "go.mod",
  "go.sum",
  "packaging/dl/*",
  "packaging/logo.svg",
  "buf.*",
]
SPDX-FileCopyrightText = "2026 Nikolay Govorov <me@govorov.online>"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = [
  "README.md",
  "docs/**.md",
]
SPDX-FileCopyrightText = "2026 Nikolay Govorov <me@govorov.online>"
SPDX-License-Identifier = "CC-BY-4.0"
