# SPDX-FileCopyrightText: 2026 Nikolay Govorov
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "mirum"
description = "Mirum service"
version.workspace = true

build = "build.rs"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[build-dependencies]
dimidiumlabs-ui-build = { git = "https://git.dimidiumlabs.io/platform.git", rev = "d6639bb2f831afedfa0b55faf5869311b04d9d74" }

[dependencies]
dimidiumlabs-server = { git = "https://git.dimidiumlabs.io/platform.git", rev = "d6639bb2f831afedfa0b55faf5869311b04d9d74" }
dimidiumlabs-ui = { git = "https://git.dimidiumlabs.io/platform.git", rev = "d6639bb2f831afedfa0b55faf5869311b04d9d74" }

axum.workspace = true
bytesize.workspace = true
humantime-serde.workspace = true
hyper-util.workspace = true
ipnet.workspace = true
maud.workspace = true
serde.workspace = true
sqlx.workspace = true
tokio.workspace = true
tokio-util.workspace = true
toml.workspace = true
