# SPDX-FileCopyrightText: 2026 Nikolay Govorov
# SPDX-License-Identifier: AGPL-3.0-or-later

{{- if and .Values.server.enabled .Values.server.grpcRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: TCPRoute
metadata:
  name: {{ include "mirum.fullname" . }}-grpc
  labels:
    {{- include "mirum.componentLabels" (dict "root" . "component" "server") | nindent 4 }}
spec:
  {{- with .Values.server.grpcRoute.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - backendRefs:
        - name: {{ include "mirum.fullname" . }}
          port: {{ .Values.server.grpcPort }}
{{- end }}

# vim: set filetype=helm:
