// Copyright (c) 2026 Nikolay Govorov
// SPDX-License-Identifier: AGPL-3.0-or-later

Dir {
    ArchiveDir ".";
    CacheDir "/tmp/apt-cache";
};

Default {
    Packages::Compress ". gzip";
    Packages::Extensions ".deb";
};

TreeDefault {
    Packages "$(DIST)/$(SECTION)/binary-$(ARCH)/Packages";
    BinCacheDB "packages-$(DIST)-$(ARCH).db";
};

Tree "dists/stable" {
    Sections "main";
    Architectures "amd64 arm64 riscv64 ppc64le";
    Directory "pool/stable";
};

Tree "dists/nightly" {
    Sections "main";
    Architectures "amd64 arm64 riscv64 ppc64le";
    Directory "pool/nightly";
};
